Fix expected NotImplementedError in Wagtail 1.6+ (#104)
The expected behavior when using a custom AbstractMediaChooserBlock
without a render_basic is to raise NotImplementedError, but instead you
get this error:

TypeError: render_basic() got an unexpected keyword argument 'context'

This is because of an outdated signature which changed in Wagtail 1.6:

https://docs.wagtail.io/en/stable/releases/1.6.html#render-and-render-basic-methods-on-streamfield-blocks-now-accept-a-context-keyword-argument

See Issue #19 and PR #20, which fixed the example in the README but didn't
fix the intended functionality.